app/src/androidTest/java/ca/ualbert/cs/tasko/UserTest.java, app/src/main/java/ca/ualbert/cs/tasko/BidList.java, app/src/main/java/ca/ualbert/cs/tasko/Task.java, app/src/main/java/ca/ualbert/cs/tasko/User.java
So PLEASE let me know if any of this screws everyone up. But I think these changes will work better in the long run!
=> Model changes

app/src/androidTest/java/ca/ualbert/cs/tasko/UserTest.java, app/src/main/java/ca/ualbert/cs/tasko/User.java
=> Fixing UserTest

app/src/androidTest/java/ca/ualbert/cs/tasko/SearchActivityTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualbert/cs/tasko/LoginActivity.java, app/src/main/java/ca/ualbert/cs/tasko/OpeningActivity.java, app/src/main/java/ca/ualbert/cs/tasko/TaskListAdapter.java, app/src/main/res/drawable/task_background.xml, app/src/main/res/layout/task_view.xml, app/src/main/res/values/strings.xml
=> Login activity

app/src/androidTest/java/ca/ualbert/cs/tasko/AddPhotoActivityTest.java, app/src/androidTest/java/ca/ualbert/cs/tasko/AddTaskActivityTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualbert/cs/tasko/AddPhotoActivity.java, app/src/main/java/ca/ualbert/cs/tasko/AddTaskActivity.java, app/src/main/java/ca/ualbert/cs/tasko/LoginActivity.java, app/src/main/java/ca/ualbert/cs/tasko/Task.java, app/src/main/res/layout/activity_add_photo.xml, app/src/main/res/values/strings.xml
Add task activity (including adding a photo) code, tests and documentation are implemented without known bugs.
=> Add task activity

app/src/androidTest/java/ca/ualbert/cs/tasko/ViewTasksBiddedTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualbert/cs/tasko/BidList.java, app/src/main/java/ca/ualbert/cs/tasko/OpeningActivity.java, app/src/main/java/ca/ualbert/cs/tasko/TaskBiddedAdapter.java, app/src/main/java/ca/ualbert/cs/tasko/ViewTasksBiddedOnActivity.java, app/src/main/res/layout/activity_view_tasks_bidded_on.xml, app/src/main/res/layout/bidded_task_layout.xml, app/src/main/res/values/strings.xml
Note the comments in the top of ViewMyBiddedTasks Testings.
=> Task bidded

app/src/main/java/ca/ualbert/cs/tasko/ViewSearchedTaskDetailsActivity.java, app/src/main/res/layout/activity_view_searched_task_details.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Making a bid now works:
Now updates server.
Now on separate thread for performance.
Now adding a second bid by same user replaces the old one.
=> Fix make bid bugs

app/src/main/java/ca/ualbert/cs/tasko/ViewTaskDetailsActivity.java
Fixed view bids on task, should now show bids on a particular task.
=> Fix view bids on task

app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualbert/cs/tasko/LogOutActivity.java, app/src/main/java/ca/ualbert/cs/tasko/LoginActivity.java, app/src/main/java/ca/ualbert/cs/tasko/MainActivity.java, app/src/main/res/layout/content_main.xml
I added a button in main to test the logout activity, we could remove it very easily.
Fixed the weird opening activity Bug and everything with login in and login seems to work well!
=> Log out functionality

app/src/main/java/ca/ualbert/cs/tasko/Task.java
Fixed bug where tasks with no photos crashed the app. No other known bugs.
=> Fixed bug where tasks with no photos crashed the app.

app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualbert/cs/tasko/AcceptedMyTaskActivity.java, app/src/main/java/ca/ualbert/cs/tasko/ViewMyTasksActivity.java, app/src/main/java/ca/ualbert/cs/tasko/ViewTaskDetailsActivity.java, app/src/main/res/layout/activity_accepted_task.xml, app/src/main/res/layout/content_accepted_task.xml, app/src/main/res/layout/content_view_my_tasks.xml, app/src/main/res/layout/content_view_task_details.xml, app/src/main/res/layout/delete_my_task_dialog.xml, app/src/main/res/values/strings.xml
Made adjustments to multiple layout things in mytasks/mytaskdetails and implemented the setup for deletion, & editing. Began the start of the activity for acceptedmytasks
=> Delete task activity

app/src/main/java/ca/ualbert/cs/tasko/CreateAccountActivity.java
Implemented automatic insertion of "-" when writing your phone number in the phone edit text box.
=> Create account activity 

app/src/androidTest/java/ca/ualbert/cs/tasko/LoginActivityTest.java, app/src/main/java/ca/ualbert/cs/tasko/SearchResultsActivity.java, app/src/main/java/ca/ualbert/cs/tasko/TaskListAdapter.java, app/src/main/java/ca/ualbert/cs/tasko/ViewTasksBiddedOnActivity.java, app/src/main/res/layout/task_cardview_layout.xml
Clickable photos (I think), and I tried to make it so that the Adapters auto update but this seems to have been causing minor performance issues.... :(
Can someone test the photo clicking for me please. And if the app is running to slow I can try and fix some of that later!
=> Final adapter features

app/src/main/java/ca/ualbert/cs/tasko/ViewBidsAdapter.java
Just a small fix to check whether a bid is rejected when you try and accept it
=> rejected bid check

app/src/androidTest/java/ca/ualbert/cs/tasko/DataManagerTaskTest.java, app/src/androidTest/java/ca/ualbert/cs/tasko/SearchActivityTest.java, app/src/androidTest/java/ca/ualbert/cs/tasko/TaskTest.java, app/src/androidTest/java/ca/ualbert/cs/tasko/ViewTasksBiddedTest.java, app/src/main/java/ca/ualbert/cs/tasko/AcceptedMyTaskActivity.java, app/src/main/java/ca/ualbert/cs/tasko/Bid.java, app/src/main/java/ca/ualbert/cs/tasko/BidStatus.java, app/src/main/java/ca/ualbert/cs/tasko/NotificationArtifacts/NotificationFactory.java, app/src/main/java/ca/ualbert/cs/tasko/Task.java, app/src/main/java/ca/ualbert/cs/tasko/TaskListAdapter.java, app/src/main/java/ca/ualbert/cs/tasko/TaskStatus.java, app/src/main/java/ca/ualbert/cs/tasko/ViewBidsAdapter.java, app/src/main/java/ca/ualbert/cs/tasko/ViewMyTasksActivity.java, app/src/main/java/ca/ualbert/cs/tasko/ViewSearchedTaskDetailsActivity.java, app/src/main/java/ca/ualbert/cs/tasko/ViewTaskDetailsActivity.java, app/src/main/java/ca/ualbert/cs/tasko/ViewTasksIBiddedOnActivity.java
I honestly dont know what I did in this branch....
=> Bug pulvarizing

app/src/main/java/ca/ualbert/cs/tasko/NotificationArtifacts/ViewNotificationActivity.java, app/src/main/java/ca/ualbert/cs/tasko/OpeningActivity.java
Chase needs to implement this, i.e the work is in his branch
=> Implemented the framework to handle app start check

app/src/main/java/ca/ualbert/cs/tasko/Commands/DataCommands/SearchTasksCommand.java
=> SearchTasksCommand no longer returns Assigned or Done tasks

app/src/main/java/ca/ualbert/cs/tasko/ViewSearchedTaskDetailsActivity.java, app/src/main/res/layout/activity_view_searched_task_details.xml
Implemented clickable usernames for viewing searched task details
=> Implemented clickable usernames for viewing searched task details

app/src/main/java/ca/ualbert/cs/tasko/TaskListAdapter.java
=> fixed the wierd looking positioning for king stephen

app/src/main/java/ca/ualbert/cs/tasko/AcceptedMyTaskActivity.java, app/src/main/res/layout/content_accepted_task.xml
Implemented ability to delete an accepted task
=> Implemented ability to delete an accepted task

app/build.gradle, app/src/main/java/ca/ualbert/cs/tasko/ViewBidsOnTaskActivity.java, app/src/main/java/ca/ualbert/cs/tasko/ViewTasksAssignedActivity.java
just cleaned up code and added documentation
=> Alden cleanup

app/src/main/java/ca/ualbert/cs/tasko/ViewMyTasksActivity.java, app/src/main/res/layout/activity_view_my_tasks.xml
Reverting the change I made to ViewMyTasksActivity as those changes did nothing
=> Revert change imtihan made to viewmytaskactivity

app/src/main/java/ca/ualbert/cs/tasko/Task.java
=> Task class cleanup

app/src/main/java/ca/ualbert/cs/tasko/AcceptedMyTaskActivity.java, app/src/main/java/ca/ualbert/cs/tasko/data/MockDataManager.java
=> Small changes
